sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"

addons:
  apt:
    packages:
      - graphviz

cache:
  - pip
  - apt

# Install packages
install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install coverage coveralls

# Run test
script:
  - coverage run setup.py test

after_success:
  - coveralls
